package com.project_agh.payrollmanagementsystem.entities;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a job position or title within the organization.
 * <p>
 * This JPA entity maps to the "stanowisko" table in the database and stores
 * details about a specific job position, including its unique identifier,
 * name, and description. It uses Lombok annotations for automatic
 * generation of standard methods (getters, setters, constructors).
 */
@Entity
@Table(name = "stanowisko")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Position {
    /**
     * The unique identifier for the job position.
     * Mapped to the "id_stanowisko" column and configured as the primary key.
     * The value is auto-generated by the database upon persistence.
     */
    @Id
    @Column(name = "id_stanowisko", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name or title of the job position (e.g., "Senior Developer", "Manager").
     * Mapped to the "nazwa" column. This field is mandatory (not nullable) and must be unique.
     */
    @Column(name = "nazwa", unique = true, nullable = false)
    private String name;

    /**
     * A detailed description of the responsibilities, requirements, or notes for the position.
     * Mapped to the "opis" column.
     */
    @Column(name = "opis")
    private String description;
}